### ISSUE TITLE
Dask dashboards missing locally

### ISSUE THREAD

**Issue by hugobowne** [coiled/data-science-at-scale#9]
I've followed instructions from [here](https://github.com/dask/dask-tutorial) to try to get this repo up and running locally.

This is what I did from the readme:

```
conda env create -f binder/environment.yml 
conda activate data-science-at-scale
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @bokeh/jupyter_bokeh
```

then `jupyter lab`

It all went smoothly but there are no dashboards when I open the notebooks (see screenshot).

Any ideas, @jrbourbeau?

<img width="1437" alt="Screen Shot 2020-09-07 at 10 27 26 am" src="https://user-images.githubusercontent.com/4182382/92338602-c968da80-f0f4-11ea-9cee-903b91bccab1.png">

**Comment by jrbourbeau** [comment]
There's an additional step to install the Dask JupyterLab extension:

```
jupyter labextension install dask-labextension
```

**Comment by hugobowne** [comment]
thanks! Looks like I'm a step closer:

![Screen Shot 2020-09-07 at 11 19 00 am](https://user-images.githubusercontent.com/4182382/92340004-113f3000-f0fc-11ea-894c-a8a6eb8df15d.png)


Do I need to enter a Dask dashboard url or something similar?

**Comment by jrbourbeau** [comment]
You can enter the cluster dashboard link (available at `client.dashboard_link` and then click the magnifying glass icon to the right) or just click the magnifying glass icon and it should autopopulate the address

**Comment by hugobowne** [comment]
Success, many thanks
